### PR TITLE
Adds editorconfig file

### PR DESCRIPTION
**Pull request by brianjhanson**

### CODE REVIEW

**Comment by cmalven** [comment]
Before I merge this and add another dot file to the repo, I'd like to get a sense of how many people on the team currently (or may in the future) use EditorConfig, since this file won't do much if they don't.

@bernsno @molwells @michaelramuta @collinjoyce what say you?

**Comment by brianjhanson** [comment]
I would like to point out that if we all can agree to use this whitespace changes in diffs would be a thing of the past. 

Just think of the glorious future that could be ahead of us.

**Comment by cmalven** [comment]
If we do decide to use it, we'll have to figure out how to manage the fact that we have lots of projects for which 2 spaces is the standard for almost everything and 4 spaces is the standard for PHP.

**Comment by brianjhanson** [comment]
I believe it only corrects these things when you save a file. We shouldn't be editing & saving any vendor files anyways.

I haven't run into any issues using it on my last few projects but that doesn't mean they don't / won't exist.

For those who want to check out more about it, there's the [EditorConfig website](http://editorconfig.org/) and the [Sublime Plugin](https://github.com/sindresorhus/editorconfig-sublime)

**Comment by cmalven** [comment]
@brianjhanson I was referring to Craft/PHP development that _we are doing_ not editing of vendor files, but I'm pretty sure you can set indentation preferences per language in the config file.

**Comment by brianjhanson** [comment]
Good point. I guess my PHP adheres to the same standard as my css / js / anything. I wasn't aware we wanted them to be different.

I vaguely remember talking about mimicking Craft's formatting when we're writing a Craft plugin, but I don't think I've written one since then.

**Comment by bernsno** [comment]
I haven't been using editor config but would be for making _our_ php files 2 spaces rather than 4.

**Comment by cmalven** [comment]
I updated this to use a 4-space override for PHP files, since that seems to be what the vast majority of the PHP community has settled on (Laravel and Craft both use 4 spaces, WordPress uses 1 tab).

If you're all okay with this I'm good to merge.

**Comment by brianjhanson** [comment]
I'm cool with it.

**Comment by cmalven** [comment]
Any of you PHP-heads care about this? @michaelramuta @mkornatz ?

**Comment by mkornatz** [comment]
I prefer 2, but I can work with 4.

**Pull request merged**
