### PR TITLE
Adds environment label plugin as install option

### PR DESCRIPTION
**Pull request by mkornatz**
https://www.pivotaltracker.com/story/show/142412643

Adds https://github.com/madebykind/craft.labelenvironment/ as an option to be installed. By default, after installing the plugin via Craft, this is what it looks like:

screen shot 2018-02-09 at 3 11 14 pm

### CODE REVIEW

**Review by MikeMcChillin — APPROVED** [review]

**Comment by cmalven** [comment]
FYI this plugin is also available for Craft 3 via composer: https://packagist.org/packages/topshelfcraft/environment-label

**Comment by mkornatz** [comment]
Thanks @cmalven. I'll do a separate PR for that. Does Craft 3's admin behave differently enough where it's not needed? Or would that still be good to have?

**Comment by cmalven** [comment]
@mkornatz I don't think Craft 3 adds anything that changes the control panel based on environment (otherwise I don't think anyone would've bothered to port this to Craft 3).

**Comment by mkornatz** [comment]
FYI, https://github.com/onedesign/generator-one-base/pull/120

**Pull request merged**
