### PR TITLE
Readme template 2016.12.02 bhanson

### PR DESCRIPTION
**Pull request by brianjhanson**
Adds a very generic readme template on project generation.

### CODE REVIEW

**Comment by cmalven** [comment]
@brianjhanson since we're asking for a project description now we might as well also add that description to `package.json`

**Comment by brianjhanson** [comment]
Good call.

**Comment by cmalven** [comment]
Can we either a) require that the description entered has a length or b) conditionally output the description depending on whether it has a length?

**Comment by cmalven** [comment]
I guess I'd prefer the former if its possible.

**Comment by brianjhanson** [comment]
Possible and done.

**Pull request merged**
