### PR TITLE
Display JS & CSS compilation error messages in the browser (in addition to the console).

### PR DESCRIPTION
**Pull request by cmalven**
Related to #11 

Often when you're developing – especially on a smaller screen – javascript or sass compilation errors may pop up that prevent the page from loading but because you're terminal is obscured you may not notice them right away.

This PR uses Browsersync's ability to send notification messages to the browser to output the contents of these errors directly in the browser in addition to the console, calling your intention to them immediately.

While this is very nice, there is one small caveat that makes it less than ideal.

It's necessary for us to override browser syncs default notification styles, because they need to use `pre` formatting and a monospace font to display readably. However, I haven't been able to find a way to add these default styles _and_ not show Browsersync's default `Connected to Browsersync` and `Stylesheet Injected` messages, which are kind of annoying. I'm leaning slightly towards this being tolerable given the convenience of in-browser error messages, but I'll defer to the group on this tradeoff.

### CODE REVIEW

**Comment by brianjhanson** [comment]
I haven't tested this, but I think we can actually use eslint's HTML output format to create an `index.html` file in the `public` folder whenever there are errors. Valet / Apache / whatever _should_ prioritize a `.html` file over the `.php` file which would make it so you can see the errors.

**Comment by cmalven** [comment]
This PR doesn't even display linting errors, just errors in the code that prevent compilation.

**Review by brianjhanson — APPROVED** [review]
I'd like to explore outputting this to a page rather than in the notification thingy, but this is better than nothing.

**Comment by cmalven** [comment]
@brianjhanson I'd be cool with trying your page idea. The one thing that this solution does that would be difficult to replicate the separate-page-route is live injecting of the error in to the page for sass and js errors without reloading the page.

**Pull request merged**
